// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coillteoir/morningbot/ent/player"
	"github.com/coillteoir/morningbot/ent/predicate"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDiscordID sets the "discordID" field.
func (_u *PlayerUpdate) SetDiscordID(v string) *PlayerUpdate {
	_u.mutation.SetDiscordID(v)
	return _u
}

// SetNillableDiscordID sets the "discordID" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableDiscordID(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetDiscordID(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *PlayerUpdate) SetScore(v int) *PlayerUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableScore(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *PlayerUpdate) AddScore(v int) *PlayerUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetLastMessage sets the "last_message" field.
func (_u *PlayerUpdate) SetLastMessage(v time.Time) *PlayerUpdate {
	_u.mutation.SetLastMessage(v)
	return _u
}

// SetNillableLastMessage sets the "last_message" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableLastMessage(v *time.Time) *PlayerUpdate {
	if v != nil {
		_u.SetLastMessage(*v)
	}
	return _u
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdate) Mutation() *PlayerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdate) check() error {
	if v, ok := _u.mutation.Score(); ok {
		if err := player.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "Player.score": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DiscordID(); ok {
		_spec.SetField(player.FieldDiscordID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(player.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(player.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMessage(); ok {
		_spec.SetField(player.FieldLastMessage, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetDiscordID sets the "discordID" field.
func (_u *PlayerUpdateOne) SetDiscordID(v string) *PlayerUpdateOne {
	_u.mutation.SetDiscordID(v)
	return _u
}

// SetNillableDiscordID sets the "discordID" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableDiscordID(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetDiscordID(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *PlayerUpdateOne) SetScore(v int) *PlayerUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableScore(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *PlayerUpdateOne) AddScore(v int) *PlayerUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetLastMessage sets the "last_message" field.
func (_u *PlayerUpdateOne) SetLastMessage(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetLastMessage(v)
	return _u
}

// SetNillableLastMessage sets the "last_message" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableLastMessage(v *time.Time) *PlayerUpdateOne {
	if v != nil {
		_u.SetLastMessage(*v)
	}
	return _u
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdateOne) Mutation() *PlayerMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Player entity.
func (_u *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdateOne) check() error {
	if v, ok := _u.mutation.Score(); ok {
		if err := player.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "Player.score": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DiscordID(); ok {
		_spec.SetField(player.FieldDiscordID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(player.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(player.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMessage(); ok {
		_spec.SetField(player.FieldLastMessage, field.TypeTime, value)
	}
	_node = &Player{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
