// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/coillteoir/morningbot/ent/player"
	"github.com/coillteoir/morningbot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescScore is the schema descriptor for score field.
	playerDescScore := playerFields[1].Descriptor()
	// player.ScoreValidator is a validator for the "score" field. It is called by the builders before save.
	player.ScoreValidator = playerDescScore.Validators[0].(func(int) error)
}
