// Code generated by ent, DO NOT EDIT.

package player

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/coillteoir/morningbot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldID, id))
}

// DiscordID applies equality check predicate on the "discordID" field. It's identical to DiscordIDEQ.
func DiscordID(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldDiscordID, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldScore, v))
}

// LastMessage applies equality check predicate on the "last_message" field. It's identical to LastMessageEQ.
func LastMessage(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastMessage, v))
}

// DiscordIDEQ applies the EQ predicate on the "discordID" field.
func DiscordIDEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldDiscordID, v))
}

// DiscordIDNEQ applies the NEQ predicate on the "discordID" field.
func DiscordIDNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldDiscordID, v))
}

// DiscordIDIn applies the In predicate on the "discordID" field.
func DiscordIDIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldDiscordID, vs...))
}

// DiscordIDNotIn applies the NotIn predicate on the "discordID" field.
func DiscordIDNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldDiscordID, vs...))
}

// DiscordIDGT applies the GT predicate on the "discordID" field.
func DiscordIDGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldDiscordID, v))
}

// DiscordIDGTE applies the GTE predicate on the "discordID" field.
func DiscordIDGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldDiscordID, v))
}

// DiscordIDLT applies the LT predicate on the "discordID" field.
func DiscordIDLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldDiscordID, v))
}

// DiscordIDLTE applies the LTE predicate on the "discordID" field.
func DiscordIDLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldDiscordID, v))
}

// DiscordIDContains applies the Contains predicate on the "discordID" field.
func DiscordIDContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldDiscordID, v))
}

// DiscordIDHasPrefix applies the HasPrefix predicate on the "discordID" field.
func DiscordIDHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldDiscordID, v))
}

// DiscordIDHasSuffix applies the HasSuffix predicate on the "discordID" field.
func DiscordIDHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldDiscordID, v))
}

// DiscordIDEqualFold applies the EqualFold predicate on the "discordID" field.
func DiscordIDEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldDiscordID, v))
}

// DiscordIDContainsFold applies the ContainsFold predicate on the "discordID" field.
func DiscordIDContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldDiscordID, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldScore, v))
}

// LastMessageEQ applies the EQ predicate on the "last_message" field.
func LastMessageEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastMessage, v))
}

// LastMessageNEQ applies the NEQ predicate on the "last_message" field.
func LastMessageNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLastMessage, v))
}

// LastMessageIn applies the In predicate on the "last_message" field.
func LastMessageIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLastMessage, vs...))
}

// LastMessageNotIn applies the NotIn predicate on the "last_message" field.
func LastMessageNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLastMessage, vs...))
}

// LastMessageGT applies the GT predicate on the "last_message" field.
func LastMessageGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLastMessage, v))
}

// LastMessageGTE applies the GTE predicate on the "last_message" field.
func LastMessageGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLastMessage, v))
}

// LastMessageLT applies the LT predicate on the "last_message" field.
func LastMessageLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLastMessage, v))
}

// LastMessageLTE applies the LTE predicate on the "last_message" field.
func LastMessageLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLastMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Player) predicate.Player {
	return predicate.Player(sql.NotPredicates(p))
}
