name: Python Lint
run-name: ${{ github.actor }} PR being linted for code cleanliness
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."
      - run: sudo apt update
      - run: sudo apt install black isort pylint pip
      - run: pip install pyenchant
      - run: echo "Packages installed"
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: echo "Checked out into ${{ github.repository }} on branch ${{ github.ref }}"
      - run: black . --diff
      - run: pylint **/*.py --rcfile=.pylintrc
